version: 1.0.{build}-appveyor
image: Visual Studio 2015
configuration:
- Debug
- Release
before_build:
- cmd: nuget restore onset-detection.sln
build:
  project: onset-detection.sln
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
artifacts:
  - path: '**\*OnsetDetection*.nupkg'